# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0xFBB0827a3E208Ff06e7Cad279ADD18bF8b78758c"
    chainName: egoldchain
    connections:
      - token: ethereum|ethereum|0xD9d6b227B00b2A979156180ee4F74Bb2F19fA5F5
    decimals: 18
    name: Ether
    standard: EvmHypSynthetic
    symbol: ETH
  - addressOrDenom: "0xD9d6b227B00b2A979156180ee4F74Bb2F19fA5F5"
    chainName: ethereum
    connections:
      - token: ethereum|egoldchain|0xFBB0827a3E208Ff06e7Cad279ADD18bF8b78758c
    decimals: 18
    name: Ether
    standard: EvmHypNative
    symbol: ETH
